"""empty message

Revision ID: 1d022ad832ad
Revises: cfae5625eab6
Create Date: 2020-04-27 13:14:57.048931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d022ad832ad'
down_revision = 'cfae5625eab6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ssh_keys_ssh_key_name_key', 'ssh_keys', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ssh_keys_ssh_key_name_key', 'ssh_keys', ['ssh_key_name'])
    # ### end Alembic commands ###
