"""empty message

Revision ID: 5c6b59f98fe5
Revises: d4cec344276b
Create Date: 2020-06-15 17:21:35.163893

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5c6b59f98fe5'
down_revision = 'd4cec344276b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_explorer', sa.Column('ce_date', sa.Date(), nullable=False))
    op.add_column('cost_explorer', sa.Column('ce_month', sa.String(), nullable=True))
    op.drop_column('cost_explorer', 'ce_instance_monthly_bill')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cost_explorer', sa.Column('ce_instance_monthly_bill', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('cost_explorer', 'ce_month')
    op.drop_column('cost_explorer', 'ce_date')
    # ### end Alembic commands ###
