"""empty message

Revision ID: 70c62b495538
Revises: 5c6b59f98fe5
Create Date: 2020-06-15 22:23:42.344501

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c62b495538'
down_revision = '5c6b59f98fe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_explorer',
    sa.Column('ce_instance_id', sa.String(), nullable=False),
    sa.Column('ce_date', sa.String(), nullable=False),
    sa.Column('ce_instance_name', sa.String(), nullable=True),
    sa.Column('ce_month', sa.String(), nullable=True),
    sa.Column('ce_instance_daily_bill', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ce_instance_id', 'ce_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_explorer')
    # ### end Alembic commands ###
