"""empty message

Revision ID: 801278c2a562
Revises: 9dfe5370bc8c
Create Date: 2020-04-24 18:04:01.028083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801278c2a562'
down_revision = '9dfe5370bc8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('public_ip', sa.String(), nullable=True),
    sa.Column('private_ip', sa.String(), nullable=True),
    sa.Column('key_name', sa.String(), nullable=True),
    sa.Column('user_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instances')
    # ### end Alembic commands ###
