"""empty message

Revision ID: a291d264b1cd
Revises: 
Create Date: 2020-09-22 16:28:27.548901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a291d264b1cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklist_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('blacklisted_on', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('cost_explorer',
    sa.Column('ce_instance_id', sa.String(), nullable=False),
    sa.Column('ce_date', sa.String(), nullable=True),
    sa.Column('ce_instance_name', sa.String(), nullable=True),
    sa.Column('ce_month', sa.String(), nullable=True),
    sa.Column('ce_instance_daily_bill', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ce_instance_id', 'ce_date')
    )
    op.create_table('instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('public_ip', sa.String(), nullable=True),
    sa.Column('private_ip', sa.String(), nullable=True),
    sa.Column('key_name', sa.String(), nullable=True),
    sa.Column('user_ids', sa.ARRAY(sa.Integer()), nullable=True),
    sa.Column('region_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ssh_keys',
    sa.Column('ssh_key_name', sa.String(), nullable=False),
    sa.Column('ssh_key_value', sa.String(), nullable=True),
    sa.Column('ssh_key_format', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ssh_key_name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('ssh_keys')
    op.drop_table('instances')
    op.drop_table('cost_explorer')
    op.drop_table('blacklist_tokens')
    # ### end Alembic commands ###
