"""empty message

Revision ID: a83162e0870f
Revises: ea0d38689b93
Create Date: 2020-04-27 11:58:28.239170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a83162e0870f'
down_revision = 'ea0d38689b93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ssh_keys_ssh_key_name_key', 'ssh_keys', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('ssh_keys_ssh_key_name_key', 'ssh_keys', ['ssh_key_name'])
    # ### end Alembic commands ###
