"""empty message

Revision ID: cfae5625eab6
Revises: a83162e0870f
Create Date: 2020-04-27 13:10:46.429198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfae5625eab6'
down_revision = 'a83162e0870f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'ssh_keys', ['ssh_key_name'])
    op.drop_column('ssh_keys', 'ssh_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ssh_keys', sa.Column('ssh_id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'ssh_keys', type_='unique')
    # ### end Alembic commands ###
