"""empty message

Revision ID: d4cec344276b
Revises: 1d022ad832ad
Create Date: 2020-05-13 18:28:02.616357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4cec344276b'
down_revision = '1d022ad832ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cost_explorer',
    sa.Column('ce_instance_id', sa.String(), nullable=False),
    sa.Column('ce_instance_name', sa.String(), nullable=True),
    sa.Column('ce_instance_monthly_bill', sa.Float(), nullable=True),
    sa.Column('ce_instance_daily_bill', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('ce_instance_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cost_explorer')
    # ### end Alembic commands ###
