"""empty message

Revision ID: ea0d38689b93
Revises: 801278c2a562
Create Date: 2020-04-24 19:29:41.538806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea0d38689b93'
down_revision = '801278c2a562'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ssh_keys',
    sa.Column('ssh_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ssh_key_name', sa.String(), nullable=True),
    sa.Column('ssh_key_value', sa.String(), nullable=True),
    sa.Column('ssh_key_format', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ssh_id'),
    sa.UniqueConstraint('ssh_key_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ssh_keys')
    # ### end Alembic commands ###
